package org.apache.hello_world_soap_zmq;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-01-12T13:00:48.795+01:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://apache.org/hello_world_soap_zmq", name = "Greeter")
@XmlSeeAlso({org.apache.hello_world_soap_zmq.types.ObjectFactory.class})
public interface Greeter {

    @WebResult(name = "responseType", targetNamespace = "http://apache.org/hello_world_soap_zmq/types")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://apache.org/hello_world_soap_zmq/types", className = "org.apache.hello_world_soap_zmq.types.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://apache.org/hello_world_soap_zmq/types", className = "org.apache.hello_world_soap_zmq.types.SayHiResponse")
    public String sayHi();
}
